import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import './globals.css'

import { AppProviders } from '@/components/Providers'
import Sidebar from '@/components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <Script src="https://kit.fontawesome.com/cd830bd1aa.js"/>
      </head>
      <body className={inter.className}>
        <AppProviders>
          <div className='grid grid-cols-[20%_auto]'>
            <Sidebar />
            { children }
          </div>
        </AppProviders>
      </body>
    </html>
  )
}
